### ISSUE TITLE
KSS_Modul no longer exists

### ISSUE THREAD

**Issue by erzengelgames** [Kurt212/KSS#16]
Hi, iam trying to use your mod for and custom life mod, allready tried a lot, but when ever i set the modul it says it is missing as soon as i start the server. The mod is installed on there (i can access the items in shops) as long as the modul is not set in the mission, but if it is, the server is not starting properly

**Comment by Kurt212** [comment]
Hello
Error messages like "Some stuff no longer exists" usually means the mod is not installed on the server.
You say it is installed, because you can access the items, but I would suggest checking it one more time.

One more guess. You could have installed the old version, where KSS_Modul never existed. But I  doubt it

**Comment by erzengelgames** [comment]
I dont know for sure but it might keeps happening cause of i reanamed the items to my language and also the messages but i created a new key and bising file (with your brands and my as very simple changes). Maybe i did a mistake there ?

**Comment by Kurt212** [comment]
If you did't rename class KSS_Modul, this isn't a problem. The problem is that server can not find that KSS_Modul class in CfgVehicles while your missions.sqm contains information about it.
